---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: echoserver-deployment
spec:
  selector:
    matchLabels:
      app: echoserver
  replicas: 1
  template:
    metadata:
      labels:
        app: echoserver
    spec:
      containers:
      - name: echoserver
        image: {{ .Values.config.image }}
        ports:
        - containerPort: {{ .Values.config.containerPort  }}
        resources:
{{ toYaml .Values.resources | indent 12 }}
